repos:
- repo: https://github.com/homebysix/pre-commit-macadmin
  rev: v1.5.1
  hooks:
  - id: check-autopkg-recipes
    args: ['--recipe-prefix', 'com.github.swy.', '--strict']
  - id: forbid-autopkg-overrides
  - id: forbid-autopkg-trust-info
  - id: check-plists
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-added-large-files
    args: ['--maxkb=100']
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
